export const ICONS = {
  NAV_MAIN: '../../assets/icons/im2b-logo-branco.png',
  NAV_GALLERY: 'https://img.icons8.com/fluency-systems-filled/110/ffffff/stack-of-photos.png',
  NAV_STUFF: 'https://img.icons8.com/fluency-systems-filled/110/ffffff/box.png',
  NAV_ABOUT: 'https://img.icons8.com/fluency-systems-filled/110/ffffff/about.png',
  NAV_EXTRAS: 'https://img.icons8.com/fluency-systems-filled/110/ffffff/sparkling.png',
  SIDEBAR_PHOTO: 'https://img.icons8.com/fluency-systems-filled/90/ffffff/camera.png',
  SIDEBAR_VIDEO: '../../assets/icons/video.png',
  SIDEBAR_ART: 'https://img.icons8.com/fluency-systems-filled/90/ffffff/paint-palette.png',
  SIDEBAR_DESIGN: 'https://img.icons8.com/fluency-systems-filled/90/ffffff/ruler-and-pencil.png',
  FOOTER_TOP: 'https://img.icons8.com/fluency-systems-filled/100/ffffff/up.png',
  FOOTER_ARROW: 'https://img.icons8.com/fluency-systems-filled/50/ffffff/arrow.png',
  SOCIAL_LINKEDIN: 'https://img.icons8.com/ios-filled/100/ffffff/linkedin.png',
  SOCIAL_GITHUB: 'https://img.icons8.com/ios-filled/100/ffffff/github.png',
  SOCIAL_TWITTER: 'https://img.icons8.com/ios-filled/100/ffffff/twitter-x.png',
};